-- RLS Security Migration (Part 2)
-- Version: 021
-- Description: Originally added RLS for conversations, customers, processed_messages.
--              These were already covered in migration 020 — this file is now a no-op.
--              Kept for migration ordering consistency.
